import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Toaster } from "sonner";
import Image from "next/image";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<Props>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Toaster />
        <Image
          className="-z-10 "
          src="/images/background.jpg"
          alt="Background picture"
          layout="fill"
          objectFit="cover"
          objectPosition="center"
        />
        <NextIntlClientProvider messages={messages}>
          <CookiesProvider>{children}</CookiesProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
